Fix build for x86_64
HaikuArchives/BeAccessible pull request #3
Opened 2018-11-15 00:52 UTC by bach5000

BeAccessible was broken for x86_64, so I fixed up some things and it should work as shown in the screenshot in README.

Speaking of the README, I reformatted it to Markdown, added screenshots, and added build directions 😄

2018-11-15 05:16 UTC, scottmc commented
@waddlesplash or @owenca can you review this one?

2018-11-15 06:27 UTC, humdingerb requested changes
I don't have a 64bit installation at hand, so other mentors would have to test.

2018-11-15 06:27 UTC, humdingerb commented on src/BeAccessibleWindow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/BeAccessibleApp.cpp
> +#include <iostream>
While you're there, alpha-sort the includes. Also it'd be nice to group and sort headers:
posix -> native -> shared private -> app private
Add an empty line between the groups.

2018-11-15 06:27 UTC, humdingerb commented on src/BeAccessibleWindow.h
> +#include <StorageKit.h>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/ColumnDesignView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/Constants.h
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/DBListView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/DBTableTabView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/GridCell.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/DBTabView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/DelimiterView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/GridRow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/GridView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/ImportFileView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/ImportFileWindow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/PasteTableView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/PasteTableWindow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/PreviewView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/RowSummaryView.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/SQLiteManager.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/TableDataRow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/TableDesignRow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:27 UTC, humdingerb commented on src/TableWindow.cpp
> +#include <iostream>
Sort as in comment 1.

2018-11-15 06:45 UTC, scottmc commented
The readme mentions two code bases, I haven't looked that closely, but it appears we only put one into the repo? Research this and perhaps update the readme to reflect that the sqlite3 version of the original code is what is in the repo (if that is the case, I assume it is since it's using sqlite3.h).

2018-11-15 16:39 UTC, bach5000 commented
Ok... I can't count. I'll just stop numbering things :)

2018-11-15 16:50 UTC, bach5000 commented
@humdingerb Done! That was painful, but got it all done 😄 

@scottmc As for the code bases, I think you're right: the README does mention that the src directory is the sqlite3 version. I'll specify this in the readme.

2018-11-15 16:54 UTC, humdingerb approved these changes

2018-11-15 16:56 UTC, humdingerb commented
Well, you didn't have to do a separate commit for every header re-ordering... :)

2018-11-15 17:29 UTC, bach5000 commented
@humdingerb could you check my GCI task?

2018-11-15 17:40 UTC, bach5000 commented
@scottmc Is this what you wanted?

2018-11-15 18:41 UTC, merged

2018-11-16 00:17 UTC, owenca commented
@bach5000 One git command I found useful is `git commit —amend` if you like to commit often for small incremental changes. You can also squash your commits locally before pushing.